### ISSUE TITLE
postgres stored procedures for aggregate calculation

### ISSUE THREAD

**Issue by mjstealey** [RENCI/nih-exposures-api#13]
Add postgres stored procedures for:
- [x] PMIJ_AVG_24     FLOAT
- [x] PMIJ_MAX_24     FLOAT
- [x] PMIJ_AVG_7DAY   FLOAT
- [x] PMIJ_MAX_7DAY   FLOAT
- [x] PMIJ_AVG_14DAY  FLOAT
- [x] PMIJ_MAX_14DAY  FLOAT
- [x] O3_AVG_24       FLOAT
- [x] O3_MAX_24       FLOAT
- [x] O3_AVG_7DAY     FLOAT
- [x] O3_MAX_7DAY     FLOAT
- [x] O3_AVG_14DAY    FLOAT
- [x] O3_MAX_14DAY    FLOAT

Should be invokable via user script or automated task
- ~parameters: `start_date`, `end_date`, `exposure_type`~
- parmeter: `_yr` TEXT - cmaq year to calculate stats on

**Comment by lstillwe** [comment]
Michael,
Do these stored procedures get called on initialization load of the database table or after?

**Comment by mjstealey** [comment]
> Do these stored procedures get called on initialization load of the database table or after?

@lstillwe - Called after the data is loaded.

**Comment by mjstealey** [comment]
Two new functions in Postgres.

```
                                                                   List of functions
 Schema |        Name        | Result data type |                                     Argument data types                                      |  Type
--------+--------------------+------------------+----------------------------------------------------------------------------------------------+--------
 public | cmaq_grid_size     | record           | _yr text, OUT min_row integer, OUT max_row integer, OUT min_col integer, OUT max_col integer | normal
 public | cmaq_o3_pmij_stats | void             | _yr text                                                                                     | normal
(2 rows)
```

These had initially been "fancier", but were too costly time wise on the database.
Have reduced scope to just calculate what's needed, and would need to be revisited for the addition of other cmaq exposure types.

**Comment by mjstealey** [comment]
merged, closing
